services:
  mariadb:
    image: mariadb:${MARIADBVERSION}
    container_name: mariadb
    #restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${MARIADB}
    ports:
      - ${MARIADB_PORTS}:3306
    volumes:
      - ${MARIADB_PATH}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    #restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    #restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAIL=${MAIL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_TO=${MAIL_TO}
      - COOKIE=${COOKIE}
      - URL_BACK=${URL_BACK}
      - URL_FRONT=${URL_FRONT}
      - DOMAINE=${DOMAINE}
    depends_on:
      - mariadb
    volumes:
      - ./src:/app/src 
    command: npm run start:dev

#   networks:
#       - rcr_network
#   labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.rcr-api.rule=Host(`MYDOMAIN.fr`)"
#       - "traefik.http.routers.rcr-api.entrypoints=websecure"
#       - "traefik.http.routers.rcr-api.tls.certresolver=myresolver"
#       - "traefik.http.services.rcr-api.loadbalancer.server.port=3000"

# networks:
#   rcr_network:
#     external: true
