version: '3.5'

services:
  mariadb:
    image: mariadb:10.6.16
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: frenchcodearena
    ports:
      - ${MARIADB_PORTS}:3306
    volumes:
      - ${MARIADB_PATH}:/var/lib/mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - mariadb
    volumes:
      - ./src:/app/src

