services:
  mariadb:
    networks:
      - rcr_network
    image: mariadb:${MARIADBVERSION}
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${MARIADB}
    ports:
      - ${MARIADB_PORTS}:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    networks:
      - rcr_network
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    networks:
      - rcr_network
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAIL=${MAIL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_TO=${MAIL_TO}
      - COOKIE=${COOKIE}
      - URL_BACK=${URL_BACK}
      - URL_FRONT=${URL_FRONT}
      - DOMAINE=${DOMAINE}
    depends_on:
      - mariadb
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma/migrations:/usr/src/app/prisma/migrations
    command: npm run start:dev

#   networks:
#       - rcr_network
#   labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.rcr-api.rule=Host(`MYDOMAIN.fr`)"
#       - "traefik.http.routers.rcr-api.entrypoints=websecure"
#       - "traefik.http.routers.rcr-api.tls.certresolver=myresolver"
#       - "traefik.http.services.rcr-api.loadbalancer.server.port=3000"


volumes:
  mariadb_data:

networks:
  rcr_network:
    driver: bridge
