version: '3.7'

services:
  mariadb:
    image: mariadb:${MARIADBVERSION}
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${MARIADB}
    ports:
      - ${MARIADB_PORTS}:3306
    volumes:
      - ${MARIADB_PATH}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAIL=${MAIL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_TO=${MAIL_TO}
      - COOKIE=${COOKIE}
    depends_on:
      - mariadb
    volumes:
      - ./src:/app/src

  # PROD
  #  app:
  #    image: flusnhield/notre_projet_api:1.0.0
  #    container_name: nest
  #    ports:
  #      - '3000:3000'
  #    environment:
  #      - DATABASE_URL=${DATABASE_URL}
  #      - MAIL=${MAIL}
  #      - MAIL_PASSWORD=${MAIL_PASSWORD}
  #      - MAIL_HOST=${MAIL_HOST}
  #      - MAIL_TO=${MAIL_TO}
  #      - COOKIE=${COOKIE}
  #    depends_on:
  #      - mariadb
  #    volumes:
  #      - ./src:/app/src

